.travis.yml
label/label_selinux_test.go
selinux_test.go

Close #2 
It's worth noticing that this is just a stopgap to test this repository since lots of tests requires selinux on host and travis currently uses either ubuntu (no selinux) or containers (no selinux). The current Travis is testing just a subset of go-selinux right now...we need to find a way to use Fedora/Centos/RHEL hosts to run tests here.
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

*: add .travis.yml

---

label/label_selinux.go

The error message added here provides no value as the caller already
knows all the added details. However it is covering up the underyling
system error (typically `ENOTSUP`). There is no way to handle this error before
this change.
This is the same change as opencontainers/runc#1339

Don't override system error

---

.travis.yml

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

.travis.yml: use go1.8.x

---

go-selinux/label/label_selinux.go

If a caller to label.InitLabels specifies a Level, then the library
leaks one Reserved level, and also fails to Reserve the specified level.
This could lead to a potential allocation of a duplicate level which would
eliminate the SELinux separation between two containers.
This patch eliminates the leak and correctly reserves the new level.

Reserve the MCS Level if the caller overrides the default.

---

.travis.yml
go-selinux/selinux.go
go-selinux/selinux_test.go

CanonicalizeContext takes a context string and writes it to the kernel
the the kernel will return a Canonicalized version of the context which
this function returns.  This functioni can be used to see if two contexts i
are equivalent

Add CanonicalizeContext function

---

go-selinux/label/label_selinux_test.go
go-selinux/selinux.go

Certain SELinux systems are compiled without MLS/MCS Support.
This means they don't support the level field in the SELinux
label.  Without this field you can not get MCS Separation for
your containers, but you can still use type enforcement.  This
patch allows the SELinux library to work on machines without MCS/MLS enabled.

Support SELinux systems without MCS Labels

---

go-selinux/selinux.go
go-selinux/selinux_test.go

This is mostly to address https://github.com/opencontainers/selinux/issues/23
I would also like to simplify the assignment (either by using Go `init()` or `sync.Once()`, and get rid of `selinuxfsSet`), but haven't done that because the patch is intrusive enough already. Let me know if you want me do that, either right here (as a part of last commit) or as a followup.

getSELinuxfs: fix/improve/speedup plus test fixes

---

go-selinux/selinux.go

Need to cast selinuxfsMagic and buf.Type to uint32 so it will work
on both 64 bit and 32 bit systems

fix selinufsMagic definition to work on 32 bit systems

---

go-selinux/label/label_selinux.go

When program calls SetProcessLabel("") this is the equivalent to
setexeccon(NULL) in C, it sets the label of the next exec process to
the default transition.  Currently we are ignoring this call which is
wrong.

SELinux needs to be able to reset process label to ""

---

go-selinux/selinux.go
go-selinux/selinux_linux.go
go-selinux/selinux_test.go

This patch makes go-selinux at least compile on non-linux systems
Basically I stubbed out all of the public content on selinux.go
for non linux systems, and copied the original selinux.go to selinux_linux.go.

go-selinux is failing to build on non linux systems

---

go-selinux/label/label_selinux.go

I have a few bug reports where people have relabeled /tmp using
--volume /tmp:/tmp:z
Expanding the /* directories to block relabeling, to help uers from
shooting themselves in the foot.
The directories added can have multiple different labels in them and confined
domains need those labels.  If the user causes a contianer runtime to relabel
the content to container_file_t, then loots of confined domains start breaking.

Add additional directories to block global relabel.

---

.travis.yml
go-selinux/label/label_selinux.go

Currently if we have an error in the options, we will leak and allocated
SELinux label.  This change will release on error.
Also return the mountlabel, even if the user specifies to disable SELinux separation.  This keeps other containers from being able to look at this privileged
containers content, as well makeing sure all content has a label.

Release SELinux labels on error in init function.

---

go-selinux/label/label.go
go-selinux/label/label_selinux.go
go-selinux/selinux_linux.go
go-selinux/selinux_linux_test.go
go-selinux/selinux_stub.go

This allows us to refresh the database of reserved labels.

Add a command to clear all labels

---

go-selinux/label/label.go
go-selinux/label/label_selinux.go
go-selinux/label/label_selinux_stub_test.go
go-selinux/label/label_selinux_test.go
go-selinux/selinux_linux.go
go-selinux/selinux_stub.go
go-selinux/selinux_stub_test.go

Return errors on calls to NewContext and DupSecOpt when the user
passes in an SELinux label with less then three fields.
Currently this library will crash, when users pass in bad data.

Verify labels when user passes them in

---

go-selinux/label/label_selinux.go
go-selinux/label/label_selinux_test.go

Add additional paths that we want to prevent users from accidently relabeling.
Including all paths in /, and users home directories.  Also added security
files in /etc and a couple of other common paths.

Expand the list of relabel exclude paths

---

README.md

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>
Per the OCI call, it was decided to move the code of conduct file into the root of the repository. This PR will fix the location, along with the top link to it.

fixing Code of Conduct link (per OCI call)

---

go-selinux/label/label.go
go-selinux/label/label_selinux.go
go-selinux/label/label_selinux_stub_test.go
go-selinux/label/label_selinux_test.go
go-selinux/selinux_linux.go
go-selinux/selinux_stub.go
go-selinux/selinux_stub_test.go

Kernel keyring patches in the kernel might allow us to
use kernel keyring with containers.  This patch allows us
to start labeling the kernel keyring to match the container.

Add interfaces to setup kernel keyring labeling

---

go-selinux/selinux_linux.go

The current setting of the kernel is failing to set the kernel keyring
within runc.  Changing to setting the process field instead of the
thread field seems to have fixed the issue.  With this change runc
is labeling the kernel keyring correctly so that it can be used within
the container.

Need to set process attributes not task

---

go-selinux/selinux_linux.go

Some users of go-selinux attempt to set the SELinux label to ""
even on SELinux disabled systems. This can cause these apps to blow
up (runc).  Rather then complicated these tools API, we can just ignore
the attempts to set "" labels.
If the caller attempts to set a label != "", then we should continue to
attempt and fail appropriately.

Ignore attempts to setLabels "" on SELinux disabled systems

---

go-selinux/label/label_selinux.go
go-selinux/label/label_selinux_test.go

More advanced policy is going to add different file types as well
as process types.  This change allows users to specify a filetype
field when initilizing the SELinux types to use.

Allow users to specify file types was well as process types

---

go-selinux/selinux_linux.go

This is an additional mitigation for CVE-2019-16884. The primary problem
is that Docker can be coerced into bind-mounting a file system on top of
/proc (resulting in label-related writes to /proc no longer happening).
While runc is working on mitigations against permitting the mounts, this
helps avoid go-selinux from being tricked into writing to non-procfs
files. This is not a perfect solution (after all, there might be a
bind-mount of a different procfs file over the target) but in order to
exploit that you would need to be able to tweak a config.json pretty
specifically (which thankfully Docker doesn't allow).
See opencontainers/runc#2128
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

selinux: verify that writes to /proc/... are on procfs

---

go-selinux/selinux_linux.go

As it was pointed out earlier, on a freshly installed CentOS 7
system (kernel 3.10.0-957.12.2.el7.x86_64) with SELinux enabled,
the kernel does not allow to write an empty label to the keycreate
file. Here's an strace except from containerd (which uses runc
which uses go-selinux):
> 20396 openat(AT_FDCWD, "/proc/self/attr/keycreate", O_WRONLY|O_CLOEXEC) = 7
> ...
> 20396 write(7, "", 0)                   = -1 EACCES (Permission denied)
NOTE: upgrading or downgrading container-selinux makes this to go
away, so in order to reproduce you need a freshly booted system.
Here is a reproducer in C:
```
[root@kir-ce7-selinux-01 ~]# cat a.c
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>
int main(void) {
int fd, r;
fd = …
```

go-selinux/SetKeyLabel: fix for RHEL7 kernels

---

go-selinux/selinux_linux.go

Something I wanted to do 2 years ago (https://github.com/opencontainers/selinux/pull/26) but forgot :)
1. Optimize `findSELinuxfsMount()` a bit using `s.Bytes()` (less copying and garbage collecting)
2. Simplify `getSELinuxfs()` code using `sync.Once`. No functional change.

getSELinuxfs: optimize/simplify using sync.Once

---

go-selinux/xattrs.go

1. For quite some time `Lgetxattr`/`Lsetxattr` are available in `x/sys/unix`, so let's use those.
2. Simplify the `ERANGE` handling logic.

xattr: use x/sys/unix, simplify

---

go-selinux/selinux_linux.go

As suggested by @stephensmalley in https://github.com/opencontainers/selinux/pull/64#issuecomment-588264641,
Linux >= 3.17 provides `/proc/thread-self` symlink so there's no need to use `gettid()`.
Let's use this. If not available, fall back to the older method.

Use /proc/thread-self if available

---

go-selinux/selinux_linux.go
go-selinux/selinux_linux_test.go

While working on minor improvements to tests, I found out
that `SetEnforceMode()` is not working even for the root user:
```
--- FAIL: TestSetEnforceMode (0.00s)
selinux_linux_test.go:94: Enforcing Mode:  -1
selinux_linux_test.go:96: Default Enforce Mode:  1
selinux_linux_test.go:100: setting selinux mode to enforcing failed:
/sys/fs/selinux/enforce not on procfs
```
If you look closer, you'll see that `EnforceMode()` is not working either,
since it returns `-1`.
The problem is, these functions, as well as `SecurityCheckContext()`,
are using `readCon()` and `writeCon()`, which require the files
being read/written to be on `procfs`.
In these cases, though, the files are on `selinuxfs`, and the filesystem
check is not really required since we already checked that during
selinuxfs mount …

Fix EnforceMode, SetEnforceMode, and SecurityCheckContext

---

go-selinux/selinux_linux.go

Otherwise this value will be treated as `int32`, which results in an
build error in 386 environments:
```
selinux_linux.go:118:14: constant 4185718668 overflows int32
```

Add uint32 cast to unix.SELINUX_MAGIC

---

go-selinux/selinux_linux.go
go-selinux/xattrs.go

These two are really unrelated but since they are both very simple I combined both to this single PR.
1. Complete the switch to `x/sys/unix`, and remove own ST_RDONLY const.
2. Fix a corner case in lgetxattr.
lgetxattr(2) man page says:
> If size is specified as zero, these calls return the  current  size  of
> the  named extended attribute (and leave value unchanged).  This can be
> used to determine the size of the buffer that should be supplied  in  a
> subsequent  call.   (But, bear in mind that there is a possibility that
> the attribute value may change between the two calls,  so  that  it  is
> still necessary to check the return status from the second call.)
The current code does not handle the "But..." case, i.e. when the size
changes between the two calls, and the new size is …

Complete syscall -> x/sys/unix switch, fix lgetxattr corner case

---

go-selinux/selinux_linux.go
go-selinux/selinux_linux_test.go
go-selinux/selinux_stub.go
go-selinux/selinux_stub_test.go

ComputeCreateContext is the same as compute_create in libselinux and takes
source context, target context, and class index and returns
the computed transition context. The class index can be retrieved
with ClassIndex().
Signed-off-by: Joshua Brindle <joshua.brindle@crunchydata.com>

Add support for ComputeCreateContext and ClassIndex

---

go-selinux/selinux_linux.go

Some of the errors were wrapped; make sure we unwrap the error before checking the cause.

make sure the underlying error is checked

---

go-selinux/label/label_selinux.go
go-selinux/selinux_linux.go

use errors.Wrapf() to preserve the original error where possible.

use pkg/errors for all errors

---

go-selinux/selinux_linux.go
go-selinux/selinux_linux_test.go
pkg/pwalk/README.md
pkg/pwalk/pwalk.go
pkg/pwalk/pwalk_test.go

_This is a continuation of https://github.com/opencontainers/selinux/pull/85 and https://github.com/containers/common/pull/82_
**TL;DR:** This adds a parallel wrapper on top of `filetree.Walk()`, enabling multiple callbacks to be used concurrently. This is proven to speed things up. The resulting implementation is used for `Chcon()`, making it about 1.5x faster.
Please see more in commit messages. For previous discussions, see the abovementioned PRs.
NOTE that this is not as fast as https://github.com/opencontainers/selinux/pull/85. The reason is we use standard `filepath.Walk()` here, which performs the (unneeded) `os.Stat()` call on every entry, and also sorts the directory entries (which also does not make sense in many cases). So, yes, we can do better, but that means either another …

Add pkg/pwalk, make Chcon() faster

---

go-selinux/label/label.go
go-selinux/label/label_selinux.go
go-selinux/label/label_stub.go
go-selinux/label/label_stub_test.go
go-selinux/label/label_test.go

Implementing FormatMountLabel on situations built without selinux should be possible; the `context` will be ignored if no SELinux is available.

Implement FormatMountLabel unconditionally

---

go-selinux/label/label.go
go-selinux/label/label_selinux.go

Theorectially if you do not change the MCS Label then we free it and two
commands later reserve it.  If some other process was grabbing MCS Labels
at the same time, the other process could get the same label.
Now we only release the label, if we have changed the MCSlevel.
Coverity was complaining about the selinux.GetEnabled() not being checked.

Remote potential race condition, where mcs label is freed

---

go-selinux/selinux_linux.go
go-selinux/selinux_stub.go

This keeps the range as part of the global state of the package but allows users
to modify the upper bounds of the category range.
Signed-off-by: Michael Crosby <michael@thepasture.io>

Allow the category range to be changed

---

go-selinux/label/label_selinux.go

If user specifies
podman run -ti --security-opt label=filetype:usr_t ...
We are ignoring the filetype change, iff the process content is not changed.

mountLabel can be changed without changing processLabel

---

go.mod
go.sum
vendor/github.com/pkg/errors/.travis.yml
vendor/github.com/pkg/errors/Makefile
vendor/github.com/pkg/errors/README.md
vendor/github.com/pkg/errors/errors.go
vendor/github.com/pkg/errors/go113.go
vendor/github.com/pkg/errors/stack.go
vendor/modules.txt

This version provides compatibility with Go 1.13 error wrapping, and drops support for Go versions < 1.11.

vendor: update pkg/errors v0.9.1

---

pkg/pwalk/pwalk.go

Fixes: https://github.com/opencontainers/selinux/issues/108
Go race detector found a race in the code wrt err read/write:
> cd pkg/pwalk && go test -run Many -race .
> RUN   TestWalkManyErrors
> 
> WARNING: DATA RACE
> Read at 0x00c0000a0510 by goroutine 7:
>   github.com/opencontainers/selinux/pkg/pwalk.WalkN()
>       /home/kir/go/src/github.com/opencontainers/selinux/pkg/pwalk/pwalk.go:91 +0x1f8
>   github.com/opencontainers/selinux/pkg/pwalk.Walk()
>       /home/kir/go/src/github.com/opencontainers/selinux/pkg/pwalk/pwalk.go:35 +0x321
> ...
> Previous write at 0x00c0000a0510 by goroutine 8:
>   github.com/opencontainers/selinux/pkg/pwalk.WalkN.func1()
>       /home/kir/go/src/github.com/opencontainers/selinux/pkg/pwalk/pwalk.go:53 +0xa6
> ...
Indeed, we wait for all runner goroutines …

pkg/pwalk: fix data race with err

---

go-selinux/selinux_linux_test.go

`stconv.NumError.Unwrap()` was added in Go 1.14 (https://github.com/golang/go/commit/0adc89aa962aa116da5540c3248977318d360738), so compile failed on Go 1.13 and older:
WARN [runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [/home/travis/gopath/src/github.com/opencontainers/selinux/go-selinux/selinux_linux_test.go:398:10: e.Unwrap undefined (type *strconv.NumError has no field or method Unwrap)]
WARN [runner] Can't run linter goanalysis_metalinter: interfacer: failed prerequisites: buildssa@github.com/opencontainers/selinux/go-selinux [github.com/opencontainers/selinux/go-selinux.test]
This patch changes the test to check the .Err (which is what `Unwrap()` returns.
This was introduced in https://github.com/opencontainers/selinux/pull/103, but for some reason, …

Fix compile error on go 1.13

---

Makefile
go-selinux/selinux.go
go-selinux/selinux_linux.go
go-selinux/selinux_stub.go

This patch moves all exported public/API functions to a single location, and un-exports their (stubbed) implementations. With this approach, exported functions only have to be documented in a single place, and enforces signatures of stubbed and non stubbed implementations to match.

selinux: separate API from implementation

---

go-selinux/selinux.go

In Go, there are no guarantees which goroutine runs in which thread.
It is therefore important to wrap calls to Set{Task,Exec}Label with
runtime.LockOSThread() and runtime.UnlockOSThread() to ensure reliable
behavior of goroutine labeling.

Clarify documentation for Set{Task,Exec}Label

---

go.mod
go.sum

relates to https://github.com/willf/bitset/issues/83
https://github.com/opencontainers/selinux/pull/103#issuecomment-651861843 added a dependency on a non-tagged version of this dependency. A new version was tagged (see https://github.com/willf/bitset/issues/83), so we can now vendor the tagged version, which includes the bugfixes.
full diff: https://github.com/willf/bitset/compare/d5bec3311243...v1.1.11

go.mod: update willf/bitset v1.1.11

---

.travis.yml

Since go 1.15 is out, go 1.13 is no longer supported.

travis: add go 1.15, rm unsupported versions

---

Makefile

The previous fix (#117) was not entirely correct, since now
`GO111MODULE` env var only applies to the first command.
In fact, `GO111MODULE` setting is no longer needed, since the global
`GO111MODULE=off` was removed by commit 4ee005d6e50e, so let's remove
it from here to avoid confusion.
Also, && is not needed either.
Surely, if someone tries something like
GO111MODULE=off make vendor
it won't work, but I don't think it should.

Makefile: fix vendor (again)

---

.golangci.yml
Makefile
go-selinux/label/label_selinux_test.go
go-selinux/selinux_linux.go
go-selinux/selinux_linux_test.go

1. Bump golangci-lint.
2. Simplify its install.
3. Fix some ineffassign and errcheck warnings.
4. Use the default set of linters.

golangci revamp

---

.travis.yml

This is an alternative to #121 with a more concise travis syntax, using the matrix.
Now, git-validation and build-cross are separate things that do no make
sense to have in the matrix, so separate them out to additional jobs.
While at it, allow `go: tip` to fail.
NOTE that testing with and without selinux tag is handled by the
Makefile, so we do not add this dimension to the matrix.
Closes: #121

travis: add ppc to the matrix

---

pkg/pwalk/pwalk.go

1. Improve docs formatting (lines with spaces at BOL are rendered
as HTML pre/code, see [1]).
2. Add note to WalkN to see Walk doc for caveats.
[1] https://pkg.go.dev/github.com/opencontainers/selinux@v1.6.0/pkg/pwalk

pkg/pwalk: improve docs

---

.golangci.yml
go-selinux/label/label_selinux.go
go-selinux/label/label_selinux_test.go
go-selinux/selinux_linux.go
go-selinux/selinux_linux_test.go

Found by whitespace linter:
go-selinux/label/label_selinux.go:60: unnecessary trailing newline (whitespace)
go-selinux/label/label_selinux_test.go:160: unnecessary trailing newline (whitespace)
go-selinux/selinux_linux_test.go:51: unnecessary trailing newline (whitespace)
Fix these, enable the linter.
The warnings were:
go-selinux/label/label_selinux.go:30:66: captLocal: `Err' should not be capitalized (gocritic)
func InitLabels(options []string) (plabel string, mlabel string, Err error) {
^
go-selinux/selinux_linux.go:831:3: assignOp: replace `ORD = ORD - TIER` with `ORD -= TIER` (gocritic)
ORD = ORD - TIER
^
go-selinux/selinux_linux.go:835:2: assignOp: replace `ORD = ORD + TIER` with `ORD += TIER` (gocritic)
ORD = ORD + TIER
^
go-selinux/selinux_linux.go:853:10: elseif: can replace …

lint: fix warnings from whitespace and gocritic, enable those

---

go-selinux/selinux_linux.go
go-selinux/xattrs.go

Wrap some syscalls (lgetattr, lsetattr, fstatfs, statfs)
to retry on EINTR, just in case.
Related:
- https://github.com/containers/storage/pull/757
- https://go-review.googlesource.com/c/go/+/249178
- https://github.com/golang/go/issues/38033

go-selinux: retry on EINTR

---

go-selinux/selinux.go
go-selinux/selinux_linux.go
go-selinux/selinux_linux_test.go
go-selinux/selinux_stub.go

This PR:
- implements get_default_context_with_level() from libselinux.
- change parser code for the SELinux config and label files to use bufio.Scanner
- cache the SELinux root policy dir value

Implement get_default_context_with_level() from libselinux

---

README.md

URL was broken -- update to the new .md
Fixes: #128
Signed-off-by: Eric Ernst <eric.g.ernst@gmail.com>

readme: update security URL

---

Makefile
README.md
go-selinux/doc.go
go-selinux/label/label_linux.go
go-selinux/label/label_linux_test.go
go-selinux/label/label_stub.go
go-selinux/label/label_stub_test.go
go-selinux/selinux_linux.go
go-selinux/selinux_linux_test.go
go-selinux/selinux_stub.go
go-selinux/selinux_stub_test.go
go-selinux/xattrs_linux.go

This project is matured enough and does not have any cgo dependency, so "selinux" build tag can be removed safely.
Close #130

Remove "selinux" build tag

---

go-selinux/doc.go

Follow-up to #132
Sorry I missed this

doc.go: remove outdated description about the build tag

---

.travis.yml
Makefile

I am going to submit mips64le architecture，The main reasons are:
1、The mips64le architecture is also the mainstream cpu architecture (amd64, arm64), which is used by many users;
2、Golang supports cross compilation, and mips64le is officially supported;
Therefore, I hope that the release package also supports the mips64le architecture, which is convenient for more users.
Signed-off-by: houfangdong houfangdong@loongson.com

support mips64le architecture.

---

go-selinux/label/label_linux.go
go-selinux/label/label_linux_test.go
go-selinux/label/label_stub_test.go
go-selinux/selinux.go
go-selinux/selinux_linux.go
go-selinux/selinux_stub.go

Currently each privileged container is reserving a different category
to make sure that other containers can not see their content. This
wastes container categories.  This PR will reserve one category for
all privileged containers (s0:c1023,c1024), and free all of the
other categories for confined containers.

Reserve one Category for the privileged containers to use

---

pkg/pwalk/pwalk.go

spotted these while reviewing https://github.com/opencontainers/selinux/pull/150, which had these fixed in the new implementation

pkg/pwalk: fix minor docs issues

---

go-selinux/rchcon.go
go-selinux/rchcon_go115.go
go-selinux/selinux_linux.go
pkg/pwalk/README.md
pkg/pwalkdir/README.md
pkg/pwalkdir/pwalkdir.go
pkg/pwalkdir/pwalkdir_test.go

TL;DR: speed up chcon for up to 1.5x to 2x with Go 1.16+.
1. pkg/pwalkdir: add
This is a copy-paste implementation of pwalk but utilizing
filepath.WalkDir instead (added in Go 1.16). As WalkDir do not call
stat(2) on every entry, it is much (2x on my machine) faster than Walk
(see below).
The idea is to have pwalk and pwalkdir coexist for some time, then
gradually retire pwalk once Go < 1.16 is unsupported.
2. Chcon: speedup for Go 1.16+
Using the newly added pwalkdir, the benchmark added by and described
in commit ba956cafe09661021bf shows a considerable speed improvement
(0.8s with pwalk, 0.5s with pwalkdir, 0.9s with chcon from GNU coreutils).

Add pwalkdir, speed up chcon

---

go-selinux/selinux_linux.go
go-selinux/selinux_linux_test.go

`fmt.Sprintf` is slow. Let's use string concatenation instead, and avoid
looking up level label twice.
Benchmark shows 3x improvement in performance, and less allocations.
```
name          old time/op    new time/op    delta
ContextGet-4     277ns ± 1%      93ns ± 1%  -66.55%  (p=0.016 n=4+5)
name          old alloc/op   new alloc/op   delta
ContextGet-4      128B ± 0%       64B ± 0%     ~     (p=0.079 n=4+5)
name          old allocs/op  new allocs/op  delta
ContextGet-4      5.00 ± 0%      1.00 ± 0%     ~     (p=0.079 n=4+5)
```
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>

(Context).get: speedup

---

go-selinux/selinux_linux.go

The errors returned from os are usually descriptive enough
(i.e. they contain the file name and the failed operation).
Fixes: bb3d708b

writeCon: no need to wrap os.Write error

---

go-selinux/selinux_linux.go
go-selinux/selinux_linux_test.go

When looking at runc strace output, I noticed that selinux attr files
are read byte by byte:
read(8, "u", 1) = 1
read(8, "n", 1) = 1
....
Apparently, this happens because fmt.Fscanf("%s") works that way.
Let's read the whole file via ioutil.ReadAll instead.
The added benchmark shows a drastic improvement:
```
name            old time/op    new time/op    delta
CurrentLabel-4    26.4µs ± 1%     4.3µs ± 1%   -83.73%  (p=0.004 n=6+5)
name            old alloc/op   new alloc/op   delta
CurrentLabel-4      352B ± 0%      776B ± 0%  +120.45%  (p=0.002 n=6+6)
name            old allocs/op  new allocs/op  delta
CurrentLabel-4      9.00 ± 0%      7.00 ± 0%   -22.22%  (p=0.002 n=6+6)
Note that increased allocation size is caused by the fact that ReadAll
preallocates a 512 bytes buffer, which is …
```

readCon speedup

---

go-selinux/label/label_linux.go
go-selinux/selinux.go
pkg/pwalk/pwalk.go
pkg/pwalk/pwalk_test.go
pkg/pwalkdir/pwalkdir.go
pkg/pwalkdir/pwalkdir_test.go

Modify pwalk and pwalkdir to make sure the path itself is added last.
This adds a guarantee that Chcon/Relabel will relabel the top-level
directory (i.e. the argument) only after all its descendants are
relabeled, thus creating a possibility to do conditional relabeling.
Benchmarks showed no noticeable difference in performance.

Chcon,Relabel: process the argument last

---

go-selinux/selinux.go
go-selinux/selinux_linux.go
go-selinux/selinux_stub.go
go-selinux/xattrs_linux.go

SELinux C library has two functions for dealing with file labels, one
which follows symlinks and one that does not.
Golang bindings should work the same way.  The lack of this function is
resulting in https://github.com/containers/buildah/pull/3630 which has
to hack around the problem.

Add LFileLabel and LSetFileLabel

---

go-selinux/rchcon.go
go-selinux/rchcon_go115.go

Signed-off-by: Tobias Polley <polley@predic8.de>

Relabel: relabel links instead of their targets

---

go-selinux/selinux_linux.go

We already check to make sure users do not accidentily relabel these excluded paths:
exclude_paths := map[string]bool{
"/":           true,
"/bin":        true,
"/boot":       true,
"/dev":        true,
"/etc":        true,
"/etc/passwd": true,
"/etc/pki":    true,
"/etc/shadow": true,
"/home":       true,
"/lib":        true,
"/lib64":      true,
"/media":      true,
"/opt":        true,
"/proc":       true,
"/root":       true,
"/run":        true,
"/sbin":       true,
"/srv":        true,
"/sys":        true,
"/tmp":        true,
"/usr":        true,
"/var":        true,
"/var/lib":    true,
"/var/log":    true,
}
But some users put homedirectories under /usr, and I see no reason to block them from relabeling.
At a certain point if users do something dumb with relableing we can not …

Allow relabeling of files/directories under /usr prefix

---

go-selinux/rchcon.go
go-selinux/selinux_linux.go

Currently if a user attempts to chcon a file or directory and fails for
any reason check if the file already has the right label, and continue.

If chcon fails, check if label is already correct

---

.github/workflows/validate.yml
go-selinux/label/label_linux_test.go
go-selinux/label/label_stub_test.go
go-selinux/selinux_linux.go
go.mod
pkg/pwalk/pwalk_test.go
pkg/pwalkdir/pwalkdir_test.go
vendor/modules.txt

See individual commits for details

gha: add go1.19, drop go1.16, update golangci-lint to v1.49

---

go-selinux/selinux.go
go-selinux/selinux_linux.go
go-selinux/selinux_stub.go

Both implementations were the same, so no stub is needed.

go-selinux: remove redundant stub for DisableSecOpt()

---

pkg/pwalk/pwalk.go

The package was already deprecated in the README, but not in code. This patch marks the code as deprecated, as go1.15 reached EOL, so all consumers should be able to use the new package.
In a follow-up, we can make these functions an alias for the new package (or remove it altogether).

pkg/pwalk: deprecate in favor of pkg/pwalkdir

---

go-selinux/selinux.go
go-selinux/selinux_linux.go
go-selinux/selinux_stub.go
go-selinux/selinux_stub_test.go

See individual commits for details

go-selinux: some cleanup/refactor and improve test coverage

---

go-selinux/selinux_linux.go

Originally, this package was documented to be for paths separated by forward slashes, but I was recently pointed to the updated package description, which amended the documentation (see https://go-review.googlesource.com/32423) and added:
> To manipulate operating system paths, use the path/filepath package.
A later patch (https://go-review.googlesource.com/45653) tweaked the description again, adding to the `path/filepath` package:
> To process paths such as URLs that always use forward slashes regardless of
> the operating system, see the path package.
And to the `path` package
> This package does not deal with Windows paths with drive letters or backslashes;
> to manipulate operating system paths, use the path/filepath package.
I expect it to be "fine" in general to use the `path` …

use filepath instead of path

---

.github/workflows/validate.yml
.golangci.yml
go-selinux/selinux.go
go-selinux/selinux_linux.go
go-selinux/selinux_linux_test.go
pkg/pwalk/pwalk.go
pkg/pwalk/pwalk_test.go
pkg/pwalkdir/pwalkdir.go
pkg/pwalkdir/pwalkdir_test.go

- follow-up to https://github.com/opencontainers/selinux/pull/189
(more coming after this, but I have ETOOMANYBRANCHES already)

golangci-lint: enable more linters and address linting issues

---

go-selinux/label/label_stub_test.go
go-selinux/selinux_linux_test.go
go-selinux/selinux_stub_test.go

updates: 1b18907dde2de75c9762d425c862586e1f7c438a (https://github.com/opencontainers/selinux/pull/169)

go-selinux: add coverage for LfileLabel, LsetFileLabel

---

.github/workflows/validate.yml
go.mod

Signed-off-by: Austin Vazquez <macedonv@amazon.com>

Add Go 1.20 support; require Go 1.19; drop Go 1.17 and 1.18

---

go-selinux/label/label.go
go-selinux/label/label_test.go

SELinux supports mounting file systems with multiple different file system types, adding new interface FormatMountLabelByType, allows the caller to specify the SELinux context type to mount the file system with.
Mount supports multiple different file system types.
context, fscontext, rootcontext, defcontext.

Add ability to set fscontext mounts points

---

go-selinux/selinux_linux.go
go-selinux/xattrs_linux.go

golangci-lint v1.54.2 comes with errorlint v1.4.4, which contains the fix [1] whitelisting all errno comparisons for errors coming directly from x/sys/unix. Thus, these annotations are no longer necessary. Remove those.
Except, the errors that do not come directly from a function in unix package still need to be annotated (see [2]).
[1] https://github.com/polyfloyd/go-errorlint/pull/47
[2] https://github.com/polyfloyd/go-errorlint/issues/55
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>

Remove nolint annotations for unix errno comparisons

---

.github/workflows/validate.yml

1. Bump actions/setup-go to v4 which enables caching by default. Disable cache for cases when golangci-lint is used.
2. Remove 'stable:' property from actions/setup-go (not needed since at least v3).
3. Bump tim-actions/get-pr-commits to v1.3.0  (fixes node compatibility).

ci: bump some actions

---

.codespellrc
.github/workflows/validate.yml
Makefile
go-selinux/selinux_linux.go
pkg/pwalkdir/README.md

1. Fix Makefile.
2. Add TODO to remove min/max.
3. Add codespell to CI.

Misc nitpicks

---

pkg/pwalk/README.md
pkg/pwalk/pwalk.go
pkg/pwalk/pwalk_test.go
pkg/pwalkdir/README.md
pkg/pwalkdir/pwalkdir.go
pkg/pwalkdir/pwalkdir_test.go

In some cases, when file walk is racing with removal, the ENOENT is
received by filepath.Walk[Dir], rather than by the callback.
Do ignore such errors, except for the root directory (Walk argument).
Modify the doc accordingly, and add a couple of test cases.
The "Race" test case, when testing the code before the fix, fails 100%
of times for pwalk and 90% for pwalkdir. Alas, I was unable to make it
fail 100% of the times without significantly increasing the test
complexity.
Fixes: #199

pwalk, pwalkdir: fix walk vs remove race

---

.github/workflows/validate.yml

N/A
This change updates actions/checkout to v4, actions/setup-go to v5, golangci/golangci-lint-action to v4 to resolve NodeJS 16 deprecation warnings.
CI passes with reduced deprecation warnings.
After

Update GitHub Actions packages to resolve deprecation warnings.

---

go-selinux/selinux_linux.go

We are seeing EINVAL errors with container engines setting SELinux labels. It would be helpful to see what Labels the engines are trying to set.

Show SELinux label on failure

---

.github/workflows/validate.yml

Lima (http://lima-vm.io) is used to create VM of these distros.
Close #220

CI: add AlmaLinux 8, CentOS Stream 9, and Fedora

---

.github/workflows/validate.yml

Tumbleweed uses SELinux since snapshot 20250211
https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/thread/G3W5NIY3OKRBHPHWTPYEUPSS4LKZN77N/

CI: add openSUSE Tumbleweed

---

go-selinux/label/label.go
go-selinux/label/label_linux.go
go-selinux/label/label_linux_test.go
go-selinux/label/label_stub.go
go-selinux/label/label_stub_test.go
go-selinux/selinux_linux_test.go

This was mostly deprecated in 2020 and I was not able to find any existing users (except for very old vendor directories in a dozen of unmaintained repos).
Time to move on.

label: remove deprecated stuff

---

.github/workflows/validate.yml
go-selinux/selinux.go
go-selinux/selinux_linux.go
go-selinux/selinux_linux_test.go

Fixes: #222
Fixes: #225
Please review commit by commit. See individual commits for details.
Ideally, I'd like this to be merged after #218 and #223.

Improve SetKeyCreate error reporting, fix test flakes

---

.github/workflows/validate.yml
.golangci.yml
go-selinux/label/label_linux.go

The configuration was migrated using golangci-lint migrate and when
tweaked manually trying to minimize it.
Also, fix some new warnings reported by updated staticcheck.

Switch to golangci-lint v2

---

go-selinux/selinux_linux.go

Commit 965323e01c4e ("SetKeyLabel: add thread group leader requirement")
added verification that the caller of SetKeyLabel is the thread-group
leader, however the check had a typo in it, which would almost always
cause all errors to be treated as ErrNotTGLeader.
It's a bit of a shame that os.Getuid() and os.Getpid() are untyped, as a
one-character typo like this can really easily cause bugs without type
checking...
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

keyring: fix typo in EACCES check

---

.github/workflows/validate.yml
pkg/pwalk/pwalk_test.go
pkg/pwalkdir/pwalkdir_test.go

See individual commits for details.
Closes: #231.

Add Go 1.25, drop go 1.23, bump golangci-lint
