opencontainers/selinux

label/label_selinux.go
runc will remove it.
Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>
=> Do not use selinux package in runc

.travis.yml, Makefile, go-selinux/label/label.go, go-selinux/label/label_selinux.go, go-selinux/label/label_selinux_test.go, go-selinux/selinux.go, go-selinux/selinux_test.go
Modify bindings to pass golint.
Make .travis.yml test that pull requests pass golint.
=> Add support for golint

Makefile, go-selinux/selinux.go
Signed-off-by: Antonio Murdaca <runcom@redhat.com>
=> go-selinux: fix lint

.pullapprove.yml
Signed-off-by: Antonio Murdaca <runcom@redhat.com>
=> .pullapprove.yml: fix array def

.pullapprove.yml
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Fix Pull Approve to reference correct team

go-selinux/selinux.go, go-selinux/selinux_test.go
This contains a bunch of minor cleanups and idiomatic fixes.
Signed-off-by: Luca Bruno <luca.bruno@coreos.com>
=> selinux: minor and idiomatic cleanups

go-selinux/selinux.go
Signed-off-by: baude <bbaude@redhat.com>
=> go-selinux/selinux.go: fix return value for FSCreateLabel

go-selinux/selinux.go
=> Another missing interface for non linux

Makefile, go-selinux/label/label.go, go-selinux/label/label_selinux.go, go-selinux/label/label_selinux_stub_test.go, go-selinux/label/label_selinux_test.go, go-selinux/selinux_linux.go, go-selinux/selinux_stub.go, go-selinux/selinux_stub_test.go
=> Add label.SetSocketCreate method

README.md
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>
https://github.com/opencontainers/org/issues/3
=> updating CoC link and security link

go-selinux/selinux_linux.go, go-selinux/selinux_stub.go, go-selinux/selinux_stub_test.go
Add SetTaskLabel, which is equivalent to setexeccon()
Add PeerLabel, which is equivalent to getpeercon()
Signed-off-by: Joshua Brindle <joshua.brindle@crunchydata.com>
=> Add SetTaskLabel() and PeerLabel()

go.sum
To keep the builds reproducible.
=> Add go.sum file

.travis.yml, Makefile
This adds cross compilation targets to travis to avoid issues when
building for different platforms.
=> Add cross build to travis

go-selinux/selinux_linux.go, go-selinux/xattrs.go
This was just an empty wrapper now
=> Remove unneeded lsetxattr() wrapper

go-selinux/label/label_selinux.go
=> go-selinux/label/label_selinux.go: gofmt

MAINTAINERS
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
=> MAINTAINERS: add Sebastiaan

Makefile, go-selinux/selinux_stub.go
=> Make sure selinux and nonselinux exported functions match

Makefile
=> Fix Makefile to now build temp files when not temp

README.md, go-selinux/doc.go, go-selinux/label/label_stub.go, go-selinux/label/label_stub_test.go, go-selinux/selinux_stub.go
=> Document the selinux build tag

.golangci.yml, Makefile, go-selinux/label/label_stub_test.go, go-selinux/selinux_stub_test.go
... to cover the entire codebase.
Fix a few newly found issues in tests.
=> golangci-lint: make sure to run with and without selinux tag

.github/workflows/validate.yml, go-selinux/label/label_linux_test.go
* switch to go 1.16 final
* go-selinux/label/label_linux_test.go: nits
=> ci: switch to go 1.16 final

go-selinux/selinux.go, go-selinux/selinux_linux.go, go-selinux/selinux_stub.go
As in https://github.com/SELinuxProject/selinux/blob/master/libselinux/src/enabled.c#L29
Closes #176.
=> Adds MLSEnabled function.
